---
# tasks file for ansible-nginx-docker-compose

- name: "Install dependencies required by this role"
  package:
    name: "{{ item }}"
  loop:
    - docker
    - docker-compose

- name: "Create directories in host for config files"
  file:
    name: "{{ nginxdc_compose_cfg_dir }}/{{ item }}"
    state: directory
  loop:
        - "nginx/conf.d"

- name: "Create docker compose file from template"
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ nginxdc_compose_cfg_dir }}/docker-compose.yml"
  tags: nginxdc-compose-cfg

- name: "Create nginx main configuration from template"
  template:
    src: "{{ nginxdc_nginx_conf_template }}.j2"
    dest: "{{ nginxdc_compose_cfg_dir }}/nginx/nginx.conf"
  tags: nginxdc-nginx-cfg

- name: "Create nginx site configuration from templates"
  template:
    src: "{{ item }}.j2"
    dest: "{{ nginxdc_compose_cfg_dir }}/nginx/conf.d/default.conf"
  loop: "{{ nginxdc_nginx_conf_d_templates }}"
  tags: nginxdc-nginx-site-cfg-create
  
- name: "start all compose services"
  docker_compose:
    project_src: "{{ nginxdc_compose_cfg_dir }}"
    state: present
    restarted: yes
  tags: nginxdc-compose-restart
  
- name: Copy nginx main configuration
  shell: docker cp "{{ nginxdc_compose_cfg_dir }}/nginx/nginx.conf" nginx:/etc/nginx/nginx.conf
  
- name: Copy nginx site configuration
  shell: docker cp "{{ nginxdc_compose_cfg_dir }}/nginx/conf.d/default.conf" nginx:/etc/nginx/conf.d/default.conf
     
- name: Copy cat.jpg
  shell: docker cp ./ansible-nginx-docker-compose/templates/cat.jpg nginx:/etc/nginx/cat.jpg
  
- name: "(Re-)start all compose services"
  docker_compose:
    project_src: "{{ nginxdc_compose_cfg_dir }}"
    state: present
    restarted: yes
  tags: nginxdc-compose-restart
